version: "3"
services:
  animal-management_web:
    container_name: animal-management_web
    build: ./docker/web
    ports:
      - "8080:80"
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - animal-management_app

  animal-management_app:
    container_name: animal-management_app
    build: ./docker/app
    volumes:
      - ./src:/var/www/src
    working_dir: /var/www/src
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=animal-management_db
      - DB_PORT=3306
      - DB_DATABASE=animal-management_db
      - DB_USERNAME=phper
      - DB_PASSWORD=secret

    depends_on:
      - animal-management_db

  animal-management_db:
    container_name: animal-management_db
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=animal-management_db
      - MYSQL_USER=phper
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
